version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./forum-backend
    container_name: forum-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build: ./forum-frontend
    container_name: forum-frontend
    restart: always
    ports:
      - "4200:4200"

volumes:
  mongodb_data:
